server:
  port: 3344

spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/coderZYGui/springcloud-config.git # 仓库地址
          search-paths:
            - springcloud-config
      label: master #读取分支

#添加rabbitmq相关支持
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#rabbitmq相关配置，暴露bus舒心配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'  #为什么配置 bus-refresh，看传染病那张图


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
